"""
Name: Kesnel Mezinord & Colin Largen
Date: 11/04/25
Assignment: Assignment #4
Due Date: 11/04/25
About this project: A simple telnet-style client to connect to the 
chat server. It handles the login protocol and the command-response loop.
Assumptions: Assumes the server is running and the port is correct.
All work below was performed solely by Kesnel Mezinord & Colin Largen.
I did use code generated by an AI tool.
"""

import socket
import sys

# Note: Your recv_message function was defined but never used,
# so I've removed it for clarity.

n = len(sys.argv)
if (n != 3):
    print("Usage: python assignment4_client.py <server_name> <port>")
    exit()

s = socket.socket()

try:
    s.connect((sys.argv[1], int(sys.argv[2])))
except socket.error as errorMessage:
    print(f'failed to connect. [{errorMessage}]')
    exit()

# --- CORRECTED LOGIN FLOW ---

try:
    # 1. Receive Pre-login Message
    beginningMsg = s.recv(1000)
    if not beginningMsg:
        print("Server closed connection.")
        exit()
    print(beginningMsg.decode(), end='') # Use end='' to avoid extra newlines

    # 2. Receive Username Prompt, Send Username
    userPrompt = s.recv(1000)
    if not userPrompt:
        print("Server closed connection.")
        exit()
    
    user = input(userPrompt.decode())
    s.send((user + '\n').encode()) # Send with newline

    # 3. Handle Server's Response (Password, Guest, or Error)
    response1 = s.recv(1000)
    if not response1:
        print("Server closed connection.")
        exit()
    
    response1_decoded = response1.decode()
    print(response1_decoded, end='')

    # Path A: Registered User - Server asks for password
    if "Enter your password:" in response1_decoded:
        password = input() # Prompt is already printed by the server
        s.send((password + '\n').encode())

        # Server sends "Incorrect password..." OR "Welcome..."
        response2 = s.recv(1000)
        if not response2:
            print("Server closed connection.")
            exit()
        
        response2_decoded = response2.decode()
        print(response2_decoded, end='')

        # Check for login failure
        if "Incorrect password" in response2_decoded:
            s.close()
            exit()
        # If we are here, login was successful and the "Welcome" message was printed.

    # Path B: Guest User - Server sends two info messages
    elif "User" in response1_decoded and "not found" in response1_decoded:
        # Server sends "Use 'register...'"
        response2 = s.recv(1000)
        if not response2:
            print("Server closed connection.")
            exit()
        print(response2.decode(), end='')

        # Server sends "Welcome..."
        response3 = s.recv(1000)
        if not response3:
            print("Server closed connection.")
            exit()
        print(response3.decode(), end='')
        
    # Path C: Already logged in error
    elif "User is already logged in" in response1_decoded:
        s.close()
        exit()

    # --- CORRECTED MAIN LOOP ---
    
    while True:
        # 1. Receive the command prompt
        promptMsg = s.recv(1000)
        if not promptMsg:
            print("\nServer connection lost.")
            break
        
        # 2. Get command from user and send it
        cmd = input(promptMsg.decode())
        if not cmd: # Handle empty input
            cmd = " " # Send something to avoid server loop
            
        s.send((cmd + '\n').encode())

        # 3. Handle quit/exit
        if cmd.lower() == "exit" or cmd.lower() == "quit":
            goodByeMsg = s.recv(1000)
            print(goodByeMsg.decode())
            s.close()
            break
            
        # 4. ***THIS IS THE MISSING STEP***
        # Receive the command's *response* from the server
        response = s.recv(1000)
        if not response:
            print("\nServer connection lost.")
            break
        print(response.decode(), end='') # Print the response

except (socket.error, BrokenPipeError, ConnectionResetError):
    print("Connection to server failed.")
except KeyboardInterrupt:
    print("\nDisconnecting...")
    s.close()
finally:
    s.close()