"""
Name: Kesnel Mezinord & Colin Largen
Date: 10/28/25
Assignment: Assignment #4
Due Date: 11/04/25
About this project: (write a small blurb about what this project's goals are/what tasks it accomplishes)
Assumptions: (write any assumptions made here (ex: assumes correct user input))
All work below was performed solely by (Your Name).
I did use code generated by an AI tool.
"""

from socket import *
import sys
import threading

GOODBYEMSGFILE = "./goodbye.txt"
BEFORELOGINMSGFILE = "./prelogin.txt"

beforeLoginMsg = ''
goodbyeMsg = ''

online_users = {}
user_info = {}
rooms = {}
next_room_id = 1

global_lock = threading.Lock()

def loadMsgs():
    global beforeLoginMsg
    global goodbyeMsg
    
    try:
        with open(BEFORELOGINMSGFILE, "r") as f:
            beforeLoginMsg = f.read()
    except FileNotFoundError:
        print(f"Error: {BEFORELOGINMSGFILE} not found.")
        beforeLoginMsg = "Welcome. [prelogin.txt not found]\n"
        
    try:
        with open(GOODBYEMSGFILE, "r") as f:
            goodbyeMsg = f.read()
    except FileNotFoundError:
        print(f"Error: {GOODBYEMSGFILE} not found.")
        goodbyeMsg = "Goodbye. [goodbye.txt not found]\n"
                
n = len(sys.argv)
if (n != 2):
    print("Usage: python server.py <server_port>")
    exit()

loadMsgs()

def mySendAll(sock, data):
    total_sent = 0
    data_length = len(data)

    try:
        while total_sent < data_length:
            sent = sock.send(data[total_sent:])
            if sent == 0:
                return -1
            total_sent += sent

    except Exception :
        return -1

    return 1

def handle_logout(userName):
    with global_lock:
        online_users.pop(userName, None)
        
        rooms_to_delete = []
        for room_id, room_data in list(rooms.items()):
            if userName in room_data['members']:
                room_data['members'].remove(userName)
                
            if room_data['leader'] == userName:
                rooms_to_delete.append(room_id)
                
        for room_id in rooms_to_delete:
            if room_id in rooms:
                print(f"Closing room {room_id} ({rooms[room_id]['topic']}) as leader {userName} logged out.")
                del rooms[room_id]
                
    print(f"User {userName} logged out and cleaned up.")

def processCmd(userName, sock, cmd):
    global next_room_id
    print(f"process '{cmd}' from {userName}")
    
    parts = cmd.split()
    command = parts[0].lower() if parts else ""

    try:
        if command == "who":
            response = "--- Online Users ---\n"
            with global_lock:
                if not online_users:
                    response = "No users are currently online.\n"
                else:
                    for user in online_users.keys():
                        response += f"* {user}\n"
            mySendAll(sock, response.encode())

        elif command == "status":
            target_user = userName
            if len(parts) > 1:
                target_user = parts[1]
            
            with global_lock:
                if target_user not in user_info:
                    mySendAll(sock, f"Error: User '{target_user}' does not exist.\n".encode())
                else:
                    status_msg = user_info[target_user]
                    online_status = "Online" if target_user in online_users else "Offline"
                    response = f"--- Status for {target_user} ({online_status}) ---\n"
                    response += f"{status_msg}\n"
                    mySendAll(sock, response.encode())

        elif command == "start":
            if len(parts) < 2:
                mySendAll(sock, "Error: Usage: start <topic>\n".encode())
                return
            
            topic = " ".join(parts[1:])
            with global_lock:
                room_id = next_room_id
                next_room_id += 1
                
                rooms[room_id] = {
                    'topic': topic,
                    'leader': userName,
                    'members': {userName}
                }
                mySendAll(sock, f"Room {room_id} created for topic: {topic}\n".encode())
        
        elif command == "rooms":
            with global_lock:
                if not rooms:
                    mySendAll(sock, "There are no active rooms.\n".encode())
                    return
                
                response = "--- Active Rooms ---\n"
                for r_id, r_data in rooms.items():
                    response += (f"[{r_id}] {r_data['topic']} "
                                 f"(Leader: {r_data['leader']}, "
                                 f"Members: {len(r_data['members'])})\n")
                mySendAll(sock, response.encode())

        elif command == "join":
            if len(parts) < 2:
                mySendAll(sock, "Error: Usage: join <room number>\n".encode())
                return
            
            try:
                room_id = int(parts[1])
            except ValueError:
                mySendAll(sock, "Error: Room number must be an integer.\n".encode())
                return

            with global_lock:
                if room_id not in rooms:
                    mySendAll(sock, "Error: Room does not exist.\n".encode())
                else:
                    rooms[room_id]['members'].add(userName)
                    mySendAll(sock, f"You have joined room {room_id} ('{rooms[room_id]['topic']}').\n".encode())

        elif command == "leave":
            if len(parts) < 2:
                mySendAll(sock, "Error: Usage: leave <room number>\n".encode())
                return

            try:
                room_id = int(parts[1])
            except ValueError:
                mySendAll(sock, "Error: Room number must be an integer.\n".encode())
                return
                
            with global_lock:
                if room_id not in rooms:
                    mySendAll(sock, "Error: Room does not exist.\n".encode())
                elif userName not in rooms[room_id]['members']:
                    mySendAll(sock, f"Error: You are not in room {room_id}.\n".encode())
                else:
                    rooms[room_id]['members'].remove(userName)
                    mySendAll(sock, f"You have left room {room_id}.\n".encode())
                    
                    if rooms[room_id]['leader'] == userName:
                        topic = rooms[room_id]['topic']
                        del rooms[room_id]
                        mySendAll(sock, f"As you were the leader, room {room_id} ('{topic}') has been closed.\n".encode())

        elif command == "shout":
            if len(parts) < 2:
                mySendAll(sock, "Error: Usage: shout <message>\n".encode())
                return
                
            message = " ".join(parts[1:])
            broadcast_msg = f"\n<{userName} SHOUTS>: {message}\n"
            
            with global_lock:
                users_to_message = {user: user_sock for user, user_sock in online_users.items() if user != userName}

            for user, user_sock in users_to_message.items():
                if mySendAll(user_sock, broadcast_msg.encode()) == -1:
                    print(f"Failed to shout to {user} (socket error).")

            mySendAll(sock, "Message shouted to all online users.\n".encode())
        
        elif command == "tell":
            if len(parts) < 3:
                mySendAll(sock, "Error: Usage: tell <user> <message>\n".encode())
                return
            
            target_user = parts[1]
            message = " ".join(parts[2:])
            target_sock = None
            
            with global_lock:
                if target_user not in online_users:
                    mySendAll(sock, "Error: User is not online.\n".encode())
                    return
                if target_user == userName:
                    mySendAll(sock, "You can't tell a message to yourself.\n".encode())
                    return
                
                target_sock = online_users[target_user]

            private_msg = f"\n<{userName} tells you>: {message}\n"
            if mySendAll(target_sock, private_msg.encode()) != -1:
                mySendAll(sock, f"Message sent to {target_user}.\n".encode())
            else:
                mySendAll(sock, f"Error: Could not send message to {target_user} (socket error).\n".encode())

        else:
            mySendAll(sock, f"Error: Unknown command '{command}'.\n".encode())
    
    except Exception as e:
        print(f"!!! EXCEPTION in processCmd from {userName}: {e}")
        try:
            mySendAll(sock, "An internal server error occurred while processing your command.\n".encode())
        except:
            pass


def handleOneClient(sock):

    mySendAll(sock, beforeLoginMsg.encode())
    mySendAll(sock, "Enter your username: ".encode())

    data1 = sock.recv(1000)
    if (len(data1) == 0) :
        sock.close()
        return
    
    data2 = data1.decode().split(' ')[0]
    userName = data2.replace("\t", " ").replace("\n", "").replace("\r", "")
    
    with global_lock:
        if userName in online_users:
            mySendAll(sock, "Error: User is already logged in.\n".encode())
            sock.close()
            return
        
        online_users[userName] = sock
        
        user_info.setdefault(userName, f"Hello, I am {userName}!")
    
    str = f"Welcome to the Internet Chat Room, {userName}!\n\n"
    mySendAll(sock, str.encode())

    cmdCount = 0
    mySendAll(sock, f"<{userName}:{cmdCount}> ".encode())
    
    while True:
        data = sock.recv(1000)
        if (len(data) == 0):
            print(f"Client {userName} closed connection")
            handle_logout(userName)
            sock.close()
            break

        cmd = data.decode().replace("\t", "").replace("\n", "").replace("\r", "")
        
        if not cmd:
            mySendAll(sock, f"<{userName}:{cmdCount}> ".encode())
            continue
            
        tmp = cmd.split()
        command = cmd.split()[0].lower()
        if (command == 'quit' or command == 'exit'):
            mySendAll(sock, goodbyeMsg.encode())
            handle_logout(userName)
            sock.close()
            break
        else: 
            processCmd(userName, sock, cmd)

        cmdCount = cmdCount + 1
        mySendAll(sock, f"<{userName}:{cmdCount}> ".encode())

s = socket()
h = gethostname()
port = int(sys.argv[1])
print(f"Starting server on {h} at port {port}")

try:
    s.bind((h, port))
except OSError as e:
    print(f"Error: Could not bind to port {port}. {e}")
    print("Port might be in use. Try a different port.")
    exit()

s.listen(5)
print("Server is listening for connections...")
        
while True:
    try:
        sock, addr = s.accept()
        print("Receive client connection from ", addr)
        p = threading.Thread(target=handleOneClient, args=(sock,), daemon=True)
        p.start()
    except KeyboardInterrupt:
        print("\nServer shutting down.")
        s.close()
        break
    except Exception as e:
        print(f"Error in accept loop: {e}")